### PR TITLE
docs(rapid-response): Removed extra ']'

### PR DESCRIPTION
**Pull request by legobrick**
## What this PR does / why we need it:
malfunctioning link fixed, smallest pr ever

## Checklist

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [x] Title of the PR starts with type and scope, (e.g. feat(agent,node-analyzer,sysdig-deploy):)
- [x] Chart Version bumped for the respective charts
- [x] Check GithubAction checks (like lint) to avoid merge-check stoppers

Check Contribution guidelines in README.md for more insight.

### CODE REVIEW

**Review by dark-vex — APPROVED** [review]

**Comment by lilx1ao** [comment]
not sure why loading the unit test plugin failed but we will look into it.

**Comment by aroberts87** [comment]
How did this get merged with the unit test job failing? It looks like the test failed for non-chart related issues, but still, we should not get into the practice of merging before all checks are completed.

**Comment by legobrick** [comment]
oh, sorry, I've actually seen the approval + the possibility to do that, so I moved on. Didn't notice they failed. Shall we make them required for the merge to happen?

**Comment by aroberts87** [comment]
I thought they were required already. Usually if you try to merge before checks are completed there is a whole lot of red text you need to get through. I'll double check the repository settings though

**Comment by dark-vex** [comment]
@lilx1ao from time to time I see it failing with this message
```
Run helm plugin install https://github.com/quintush/helm-unittest
Support linux-amd64
Retrieving https://api.github.com/repos/quintush/helm-unittest/releases/tags/v0.2.11
No download_url found only searching for linux
Downloading to location /tmp/_dist/
curl: Remote file name has no length!
curl: (23) Failed writing received data to disk/application
Error: plugin install hook for "unittest" exited with error
Failed to install helm-unittest
For support, go to https://github.com/kubernetes/helm
Error: Process completed with exit code 1.
```
And usually just re-run the failed job do the trick. I suspect the GH may not have the network ready and fails to download the plugin

**Comment by aroberts87** [comment]
@legobrick - I checked the repository settings and the Unit Test job was not configured to be a blocking requirement for merges to master. This was an oversight and has now been corrected. Thank you for helping us discover this loophole. 🙂

**Pull request merged**
