### PR TITLE
[sysdig] Add missing priorityClassName for nodeAnalyzer

### PR DESCRIPTION
**Pull request by jcbbc**
Now that nodeImageAnalyzer is deprecated, deployements must use the nodeAnalyzer daemonset instead. However this one was missing a templated value in order to provide a custom PriorityClass.

## Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)
- [x] PR only contains changes for one chart

### CODE REVIEW

**Comment by jcbbc** [comment]
I'm not sure why the lint fail here. It works on my side. Is there a way to have more details on where are the trailing spaces?

**Comment by airadier** [comment]
> I'm not sure why the lint fail here. It works on my side. Is there a way to have more details on where are the trailing spaces?

Hi,

forks from another repository are not allowed to use the secrets, so a templating system that is used to replace some values from secrets is not working for forks. Let me clone your PR and trigger the action from there.

**Comment by airadier** [comment]
Linter is passing now 👍

**Comment by jcbbc** [comment]
Thanks! Is there anything else needed for this PR to move forward?

**Review by achandras — APPROVED** [review]
LGTM, thanks @jcbbc!

**Pull request merged**
