### PR TITLE
Update daemonset.yaml to add the https_proxy and http_proxy in the env section of the sysdig-agent-kmodule container

### PR DESCRIPTION
**Pull request by luiof**
## What this PR does / why we need it:

Added the missing https_proxy and http_proxy in the env section of the sysdig-agent-kmodule container.
We need it since it is missing in the chart but it is supported by the container (we tested it).

## Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[mychartname]`)
- [ ] PR only contains changes for one chart

### CODE REVIEW

**Comment by dark-vex** [comment]
@achandras @yashgiri this one is quite old but it looks a good change, do you want me to rebase and do that for both sysdig and agent charts?

**Comment by achandras** [comment]
@dark-vex I agree that this is useful. If you could bring this over to both charts that would be fantastic

**Comment by dark-vex** [comment]
@achandras I will try to find some time today to-do that ;)

**Comment by dark-vex** [comment]
Closing this PR since I have created the new one:
https://github.com/sysdiglabs/charts/pull/572

**Pull request closed without merging**
