### PR TITLE
[admission-controller] Allow digest specification in values.yaml

### PR DESCRIPTION
**Pull request by climbertjh**
## Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [X] Chart Version bumped
- [X] Variables are documented in the README.md
- [X] Title of the PR starts with chart name (e.g. `[mychartname]`)
- [X] PR only contains changes for one chart

### CODE REVIEW

**Comment by achandras** [comment]
@climbertjh could you please update the README with these two new values?

**Comment by climbertjh** [comment]
> @climbertjh could you please update the README with these two new values?

I will work on that update and re-submit.

**Comment by climbertjh** [comment]
@achandras  - ok, I've updated the README.md file.

**Comment by climbertjh** [comment]
@achandras - I noticed this morning a pending lint-test is listed as expected.

Here are the results of running `make lint` on the branch:
```
1 chart(s) linted, 0 chart(s) failed
------------------------------------------------------------------------------------------------------------------------
 ✔︎ admission-controller => (version: "0.5.18", path: "charts/admission-controller")
 ✔︎ cloud-bench => (version: "0.2.1", path: "charts/cloud-bench")
 ✔︎ cloud-connector => (version: "0.7.4", path: "charts/cloud-connector")
 ✔︎ cloud-scanning => (version: "0.3.1", path: "charts/cloud-scanning")
 ✔︎ harbor-scanner-sysdig-secure => (version: "0.3.0", path: "charts/harbor-scanner-sysdig-secure")
 ✔︎ registry-scanner => (version: "0.0.27", path: "charts/registry-scanner")
 ✔︎ sysdig => (version: "1.12.56", path: "charts/sysdig")
 ✔︎ sysdig-mcm-navmenu => (version: "1.0.2", path: "charts/sysdig-mcm-navmenu")
 ✔︎ sysdig-stackdriver-bridge => (version: "1.1.1", path: "charts/sysdig-stackdriver-bridge")
------------------------------------------------------------------------------------------------------------------------
All charts linted successfully
```

I hope this helps move this along.

**Comment by achandras** [comment]
hey @climbertjh thanks for the updates! looking into why the chart install test is failing but I don't think it has to do with your changes

**Comment by achandras** [comment]
hey @climbertjh thanks for the updates! looking into why the chart install test is failing but I don't think it has to do with your changes

**Comment by climbertjh** [comment]
@achandras - thanks for picking this up again and looking at it.  Please let me know if there's anything else you need from me.  I see that the clone of this branch seems to have passed the lint checking, but failed when starting up the admission-controller-webhook container.  That seems unrelated to the changes in the PR though.

**Comment by airadier** [comment]
> @achandras - thanks for picking this up again and looking at it. Please let me know if there's anything else you need from me. I see that the clone of this branch seems to have passed the lint checking, but failed when starting up the admission-controller-webhook container. That seems unrelated to the changes in the PR though.

@achandras please note that as the PR is from a fork it won't be able to read the secrets, so that might explain the error in the installation:
```
{"level":"error","component":"webhook","time":"2022-03-21T15:39:03Z","message":"unable to register cluster 0a686674-9522-4b3d-9014-9b5389e9c83f: error from Sysdig Secure API: 401"}
```

Let me try to push the same branch and changes to the original repository and see if this fixes the issue.

**Comment by airadier** [comment]
> Let me try to push the same branch and changes to the original repository and see if this fixes the issue.

I see you already did in https://github.com/climbertjh/charts/commits/allow-digests :)

**Comment by climbertjh** [comment]
Could, possibly, `charts/admission-controller/ci/custom-ca-and-certs-values.yaml` have an out of date secrets value it? (API token for connecting to the Sysdig service)?

That file seems to be referenced during the `ct install` step of the build.

**Comment by achandras** [comment]
@climbertjh that seems to have been exactly the problem!

**Review by achandras — APPROVED** [review]
apologies for the long delays

**Comment by climbertjh** [comment]
Thanks for the attention @achandras !

**Pull request merged**
