### PR TITLE
[sysdig-deploy][agent][node-analyzer][rapid-response][admission-controller][harbor-scanner-sysdig-secure][kspm-collector] Fixed sysdig showel icon from the published charts

### PR DESCRIPTION
**Pull request by manuelbcd**
Switched icon to github draios org logo. The previous one was tied to a blog url which does not exist anymore

## What this PR does / why we need it:

The legacy logo was tied from a blog url and it was removed. Third parties like marketplaces and platforms was showing their default logos instead our custom logo.

## Checklist

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [x] Title of the PR starts with chart name (e.g. [mychartname]) 
- [x] Chart Version bumped for the respective charts
- [x] Changelog updated for the charts with version updates.
- [ ] Variables are documented in the README.md (or README.tpl in some charts) --> NA
- [x] Check GithubAction checks (like lint) to avoid merge-check stoppers
- [ ] All test files are added in the tests folder of their respective chart and have a "_test" suffix --> NA

Check Contribution guidelines in README.md for more insight.

### CODE REVIEW

**Comment by yashgiri** [comment]
Hi @manuelbcd it seems there is some issue with our CI and we are trying to debug what is causing it meanwhile can we also have the icon changes for the charts - node-analyzer, kspm-collector, rapid-response, and admission-controller.

**Comment by ironashram** [comment]
@manuelbcd [this](https://github.com/sysdiglabs/charts/actions/runs/3577018923/jobs/6015521742) is why the CI reported a failure, basically you need to bump the version on every updated chart

@yashgiri when running `/approve-test-run` only the final check status gets updated in the PR, for the logs you have to  check the Actions tab

**Review by ironashram — APPROVED** [review]
LGTM, the CI timed out on the last run but it's clearly unrelated to this changes so i'm approving

**Pull request merged**
