### PR TITLE
[node-analyzer]: update legacy components

### PR DESCRIPTION
**Pull request by mech-pig**
## Checklist

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [x] Title of the PR starts with chart name (e.g. [mychartname])
- [x] Chart Version bumped for the respective charts
- [x] Changelog updated for the charts with version updates.
- [x] Variables are documented in the README.md (or README.tpl in some charts)
- [x] Check GithubAction checks (like lint) to avoid merge-check stoppers

Check Contribution guidelines in README.md for more insight.

### CODE REVIEW

**Review by yashgiri — CHANGES_REQUESTED** [review]
Hello, these changes look good to me. Can you also include changes for sysdig-deploy chart.yaml version changes and changelog for sysdig-deploy as well.

**Comment by ProvoK** [comment]
@yashgiri he did that in a separate PR (https://github.com/sysdiglabs/charts/pull/678), isn't it the best practice to have one chart update per PR? 

also, it's better to first really release the chart and only after reference it, imvho

**Review by ProvoK — APPROVED** [review]

**Comment by mech-pig** [comment]
@yashgiri @ProvoK I've cherry-picked the commit introduced by the #678 PR. If you prefer having a single PR that updates both the subchart and the umbrella chart I will close #678 and update our internal procedures, otherwise I can simply revert the latest change>

**Review by yashgiri — APPROVED** [review]

**Comment by yashgiri** [comment]
Thank you @mech-pig 
I agree with you @ProvoK it is just that in the past during a high influx of PR a lot of people forgot to update the second sysdig-deploy chart accordingly and it always used to get missed out leading to quite some inconsistency problems.

**Pull request merged**
