### PR TITLE
[agent][node-analyzer][sysdig-deploy] Update .helmignore files

### PR DESCRIPTION
**Pull request by aroberts87**
## What this PR does / why we need it:
A previous change to the .helmignore accidentally caused the `$chart/templates/tests/` folders in some subcharts to be omitted, which prevented the use of `helm test` on our releases. This change adds them back.

## Checklist

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [x] Title of the PR starts with chart name (e.g. [mychartname])
- [x] Chart Version bumped for the respective charts
- [x] Changelog updated for the charts with version updates.
- [x] Check GithubAction checks (like lint) to avoid merge-check stoppers

Check Contribution guidelines in README.md for more insight.

### CODE REVIEW

**Comment by yashgiri** [comment]
Hi @aroberts87 I just checked "/tests/" was not present in the .helmignore of the other 3 sub charts (rapid-response, kspm-collector, admission-controller) do you think it should be a part of this PR or should I create another PR for the same?

Also thank you for these changes!

**Review by yashgiri — APPROVED** [review]

**Comment by lilx1ao** [comment]
does this pr have something to do with the test pod issue raised in one of our channels?

**Comment by yashgiri** [comment]
I believe this PR modifies my changes to helmignore which unintentionally ignored the helm test that is to be included in their packaging.

**Comment by lilx1ao** [comment]
thanks. so they wanted the test pod?

**Comment by aroberts87** [comment]
> thanks. so they wanted the test pod?

no, they don't want the test pod. i'm still trying to figure out why they're getting it, but in my investigations i found out that we had a regression in the charts and were no longer shipping out chart tests. this commit resolves that issue.

**Comment by aroberts87** [comment]
> Hi @aroberts87 I just checked "/tests/" was not present in the .helmignore of the other 3 sub charts (rapid-response, kspm-collector, admission-controller) do you think it should be a part of this PR or should I create another PR for the same?

I did not add to those files because the regression of ignoring just `tests` was not present in those `.helmignore` files. I'd be happy to make those changes in this PR if you'd like though.

**Review by lilx1ao — APPROVED** [review]
I see, thank you!

**Comment by yashgiri** [comment]
@aroberts87 I think we can keep it in mind for the next time better to get this PR in right now.

**Pull request merged**
