### PR TITLE
[CI] Adding unit test workflow for agent and nodeanalyzer

### PR DESCRIPTION
**Pull request by yashgiri**
## What this PR does / why we need it:

This PR is to add the workflow changes to add unit tests to the (Lint and test charts) workflow. Once this workflow is added the test suite in the agent and node-analyzer will always be activated and any further test changes will need to be done only in the test suites.

Also, the current tests being added are the ones checking collector endpoint and apiEndpoint values.

## Checklist

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [ ] Title of the PR starts with chart name (e.g. [mychartname])
- [ ] Chart Version bumped for the respective charts
- [ ] Changelog updated for the charts with version updates.
- [ ] Variables are documented in the README.md (or README.tpl in some charts)
- [x] Check GithubAction checks (like lint) to avoid merge-check stoppers
- [ ] All test files are added in the tests folder of their respective chart and have a "_test" suffix

Check Contribution guidelines in README.md for more insight.

### CODE REVIEW

**Comment by yashgiri** [comment]
Hi please check out the Lint and Test Charts / Unit-tests (pull_request) to see its execution.

**Review by ironashram — COMMENTED** [review]
should be ok, i was wondering one thing tho, do we need to initialize another job for this? or would it make sense to just add the steps to the already present lint-test job?, we would avoid the need to setup helm and checkout twice.

Another option would be to add the unit tests as a separate workflow
I don't have a strong opinion on this, just trying to think what would be the best going forward

**Comment by yashgiri** [comment]
That's actually a great question and I did give it quite some thought.
So I kept it in this workflow by going through this: https://docs.github.com/en/actions/using-workflows/about-workflows
it felt that since it needs to be activated on the same event which is a pr it makes sense. 
The decision to keep it in a different job was purely based on reducing CI time and improving parallelization. As we go ahead a lot of Unit tests will be automated and added to this 'Unit-tests' job and the 'lint-test' takes quite some time.

But yeah if there is any other suggestion based on some reasoning that you think is better suited we can go that way. I also do not really have a strong opinion on this.

I will wait for @aroberts87 review on this

**Review by aroberts87 — APPROVED** [review]
> do we need to initialize another job for this?

I can see the argument for both sides of this discussion, but ultimately I feel that having a different job makes the most sense. As @yashgiri mentioned before, having separate jobs helps with operational logistics with parallelization and whatnot, but it also helps logically separate two different workflows (linting vs testing).

@yashgiri - I'm good with this PR as it stands today though, feel free to adjust if you want to based on feedback, but this LGTM.

**Comment by yashgiri** [comment]
I squashed the commits and have rebased it

**Pull request merged**
