### PR TITLE
feat(node-analyzer): Allow daemonset to have maxUnavailable setting configurable

### PR DESCRIPTION
**Pull request by edify42**
## What this PR does / why we need it:

Allows for faster deployment of the node analyzer daemonset. Similar to [PR 376](https://github.com/sysdiglabs/charts/pull/376)

## Checklist

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [x] Title of the PR starts with type and scope, (e.g. feat(agent,node-analyzer,sysdig-deploy):)
- [x] Chart Version bumped for the respective charts
- [x] Variables are documented in the README.md (or README.tpl in some charts)
- [ ] Check GithubAction checks (like lint) to avoid merge-check stoppers
- [x] All test files are added in the tests folder of their respective chart and have a "_test" suffix

Check Contribution guidelines in README.md for more insight.

### CODE REVIEW

**Review by dark-vex — APPROVED** [review]
LGTM, thanks for this PR!
@mavimo @aroberts87 I've added both as reviewer for a second pair of eye before merging it

**Comment by aroberts87** [comment]
Hey @edify42! I apologies for not seeing this until now. The PR looks good to me, but since there have been a few merges to the node-analyzer chart since you opened your PR could you please resolve the conflicts in the `Chart.yaml`? Once you've done that I can can go ahead and merge this for you. Thanks!

**Comment by edify42** [comment]
> Hey @edify42! I apologies for not seeing this until now. The PR looks good to me, but since there have been a few merges to the node-analyzer chart since you opened your PR could you please resolve the conflicts in the `Chart.yaml`? Once you've done that I can can go ahead and merge this for you. Thanks!

Done! Thanks for the reviews all!

**Review by aroberts87 — APPROVED** [review]

**Pull request merged**
