### PR TITLE
docs(node-analyzer): adding the new container and host scanner

### PR DESCRIPTION
**Pull request by giuse-sysdig**
## Checklist

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [ ] Title of the PR starts with type and scope, (e.g. feat(agent,node-analyzer,sysdig-deploy):)
- [ ] Chart Version bumped for the respective charts
- [ ] Variables are documented in the README.md (or README.tpl in some charts)
- [ ] Check GithubAction checks (like lint) to avoid merge-check stoppers
- [ ] All test files are added in the tests folder of their respective chart and have a "_test" suffix

Check Contribution guidelines in README.md for more insight.

### CODE REVIEW

**Review by ironashram — CHANGES_REQUESTED** [review]
Hi @giuse-sysdig, please check https://github.com/sysdiglabs/charts/blob/master/README.md#pull-requests and conform the Title of the PR

The chart version bump is also missing

**Review by ElenaFerante — APPROVED** [review]
lgtm

**Comment by ironashram** [comment]
Thanks for updating the PR title, fyi i updated this branch with the latest master since there was a bug when you first opened this PR which was causing the `PR lint` check to not be re-triggered after updating the title, now the check is ok :rocket: 

Only thing missing is the version bump of the chart itself

**Comment by giuse-sysdig** [comment]
need to retrigger

**Review by ironashram — APPROVED** [review]

**Pull request merged**
