### PR TITLE
feat(admission-controller): Update AC to 3.9.15

### PR DESCRIPTION
**Pull request by tembleking**
## What this PR does / why we need it:

Updates the AC to 3.9.15

## Checklist

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [x] Title of the PR starts with type and scope, (e.g. feat(agent,node-analyzer,sysdig-deploy):)
- [x] Chart Version bumped for the respective charts
- [x] Variables are documented in the README.md (or README.tpl in some charts)
- [x] Check GithubAction checks (like lint) to avoid merge-check stoppers
- [x] All test files are added in the tests folder of their respective chart and have a "_test" suffix

Check Contribution guidelines in README.md for more insight.

### CODE REVIEW

**Comment by regiluze** [comment]
Hey Fede, 
missing the changelog file changes and sysdig-deploy unified char version bump :)

**Comment by ironashram** [comment]
> Hey Fede, missing the changelog file changes and sysdig-deploy unified char version bump :)

fyi adding the changelog manually is no longer needed since this morning, if the PR title matches the [requirements](https://github.com/sysdiglabs/charts/blob/master/README.md#pull-requests) an entry will be automatically added

for example in this case
`chore(admission-controller): Update AC to 3.9.15`

**Comment by tembleking** [comment]
Wow all this changed a lot since my last contribution, good to know, thanks guys!

**Comment by tembleking** [comment]
AC has not released the version yet, it's taking a while, I will reexecute the tests in an hour.

**Review by miketnt — APPROVED** [review]

**Pull request merged**
