### PR TITLE
[sysdig-deploy] Clean up the NOTES.txt file for sysdig-deploy

### PR DESCRIPTION
**Pull request by e-minguez**
## What this PR does / why we need it:

Clean the output of the chart when deploying the agent.
README now includes links to the chart components

## Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)

### CODE REVIEW

**Comment by yashgiri** [comment]
Hi @e-minguez 2 small additions - 
1. can you do a version change for the chart from 0.1.8 to 0.1.9.
2. Add a changelog comment for the small change.

**Comment by e-minguez** [comment]
Do you think it would be better to do a single PR and drop #501 ?

**Comment by yashgiri** [comment]
I do think that a single PR would be cleaner, but will have to make sure that the changelog involves these 2 minor changes mentioned in it.

**Comment by e-minguez** [comment]
> I do think that a single PR would be cleaner, but will have to make sure that the changelog involves these 2 minor changes mentioned in it.

Done. Would you mind to take a look? Thanks.

**Review by yashgiri — APPROVED** [review]

**Comment by e-minguez** [comment]
@achandras @lilx1ao would you mind to take a look?
Thanks

**Review by achandras — APPROVED** [review]

**Comment by achandras** [comment]
We will have to clone this PR to get the linter to run from this base repo.

#316 started to address this, but for the checks we have right now, since it doesn't check pod readiness, there is probably no harm in using hard-coded values in the test-values.yaml

**Comment by achandras** [comment]
@e-minguez looks like the version bump might have gotten dropped on your latest merge/rebase: https://github.com/sysdiglabs/charts/runs/7322855364?check_suite_focus=true#step:7:37

**Comment by e-minguez** [comment]
> @e-minguez looks like the version bump might have gotten dropped on your latest merge/rebase: https://github.com/sysdiglabs/charts/runs/7322855364?check_suite_focus=true#step:7:37

Would you mind to check it now? Thanks.

I think the issue is this PR didn't bumped the version https://github.com/sysdiglabs/charts/pull/503/files in the changelog (?)

**Comment by lilx1ao** [comment]
running the workflow now, let's see how it goes

**Pull request merged**
