### PR TITLE
[agent] Incorrect collector URL for us4 and au1

### PR DESCRIPTION
**Pull request by shawnjohnson**
## What this PR does / why we need it:
Fix the URL for the us4 and au1 regions

## Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)
- [x] PR only contains changes for one chart

### CODE REVIEW

**Comment by lilx1ao** [comment]
thanks for the fix. meanwhile could you update the chart version and document this in the changelog?
here is an example: https://github.com/sysdiglabs/charts/commit/463c9368656008c0cf56f38703345631e8157e5c

**Comment by shawnjohnson** [comment]
@lilx1ao Does the sysdig-deploy chart also get a patch version bump?

**Review by yashgiri — APPROVED** [review]

**Comment by lilx1ao** [comment]
@shawnjohnson I think so, but let's @achandras to be sure

**Comment by yashgiri** [comment]
It does but it can be done in a separate PR I think.

**Comment by achandras** [comment]
Yep @shawnjohnson please update the chart version in sysdig-deploy in a follow-up PR. Apologies for the manual process for the time being

**Pull request merged**
