### PR TITLE
[Sysdig] enable ksmp deploy by default

### PR DESCRIPTION
**Pull request by sameer-in**
## enable ksmp deploy by default

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [ ] Title of the PR starts with chart name (e.g. [mychartname])
- [ ] Chart Version bumped for the respective charts
- [ ] Changelog updated for the charts with version updates.
- [ ] Variables are documented in the README.md (or README.tpl in some charts)
- [ ] Check GithubAction checks (like lint) to avoid merge-check stoppers

Check Contribution guidelines in README.md for more insight.

### CODE REVIEW

**Comment by claffin** [comment]
If we change this to enabled by default, then next time a customer upgrades the Helm chart they're going to end up installing KSPM whether they actually wanted to or not. I don't think we want to do this? 

We should instead update the agent Helm install on data sources page, in the readme and docs to include `--set kspm.deploy=true`.

**Comment by aroberts87** [comment]
I agree with @claffin on this one. I don't think we want to change the defaults. The `sysdig-deploy` README shows how to enable kspm if anyone wants to deploy it. https://github.com/sysdiglabs/charts/tree/master/charts/sysdig-deploy#configuration

**Comment by yashgiri** [comment]
+1 @claffin @aroberts87

**Comment by sameer-in** [comment]
I agree @claffin. Let me close this PR.

**Pull request closed without merging**
