### PR TITLE
[sysdig] update benchmarkRunner version and fix SA creation

### PR DESCRIPTION
**Pull request by achandras**
## What this PR does / why we need it:

Prevents creation of serviceAccount, clusterrole, and clusterrolebinding when the node analyzer deployment is disabled.

## Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)
- [x] PR only contains changes for one chart

### CODE REVIEW

**Review by noahkraemer — CHANGES_REQUESTED** [review]
The `deploy-nia` value is set based on the `nodeImageAnalyzer.deploy`, which refers to the legacy Node Image Analzer daemonset, which does not use the new SA & associated objects: https://github.com/sysdiglabs/charts/blob/master/charts/sysdig/templates/_helpers.tpl#L211-L213

I think we need a new `deploy-na` helper that is based on `nodeAnalyzer.deploy` instead

**Comment by achandras** [comment]
Oh yep, missed that. I see the daemonset is using `and (not (include "deploy-nia" .)) .values.nodeanalyzer.deploy`, will make a helper using that

**Comment by achandras** [comment]
Updated, thanks for the feedback

**Review by noahkraemer — APPROVED** [review]
Great, thanks for catching this @achandras!

**Review by aq17 — APPROVED** [review]

**Pull request merged**
