### PR TITLE
[Fix] Missing cpu limits for slim agent (sysdig + agent charts)

### PR DESCRIPTION
**Pull request by dark-vex**
## What this PR does / why we need it:

There is missing the cpu limits which cause to have this error while deploying the agent (this message is coming from k8s events while describing agent daemonset):
```
Error creating: Pod "sysdig-agent-<id>" is invalid: spec.initContainers[0].resources.requests: Invalid value: "1": must be less that equal to cpu limit
```

## Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[mychartname]`)
- [X] PR only contains changes for one chart

### CODE REVIEW

**Comment by dark-vex** [comment]
Attaching also the screenshot with the error message:
chart-issue

**Comment by achandras** [comment]
@dark-vex thanks for the fix! could you please update the patch version in each Chart.yaml?

**Comment by dark-vex** [comment]
@achandras yes, sure I have updated both, let me know if it's fine now

**Comment by dark-vex** [comment]
@achandras I have pushed once again the Chart version (I noticed that it changed due to another merge)

**Review by achandras — APPROVED** [review]
lgtm!

**Pull request merged**
