### PR TITLE
[CI] Updated sysdig deploy update workflow with new PAT token

### PR DESCRIPTION
**Pull request by yashgiri**
## Checklist

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [ ] Title of the PR starts with chart name (e.g. [mychartname])
- [ ] Chart Version bumped for the respective charts
- [ ] Changelog updated for the charts with version updates.
- [ ] Variables are documented in the README.md (or README.tpl in some charts)
- [ ] Check GithubAction checks (like lint) to avoid merge-check stoppers
- [ ] All test files are added in the tests folder of their respective chart and have a "_test" suffix

Check Contribution guidelines in README.md for more insight.

### CODE REVIEW

**Comment by aroberts87** [comment]
@yashgiri - am I correct in assuming the 'P' in PAT stands for personal? In that case, what would happen to this workflow should you ever leave Sysdig?

**Comment by yashgiri** [comment]
@aroberts87  The workflow would work as intended until Feb 13, 2023 which is the expiration date of the token. After which the creation of the PR would fail. At that point, the token might have to be replaced. I can also create a token with longer expiry if needed for 2-3 years or so.
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/token-expiration-and-revocation

Edit: I realized irrespective of the token expiry date if the token holder's access is revoked the workflow would fail from the time the access is revoked.

**Review by aroberts87 — APPROVED** [review]
@yashgiri - i'm going to approve this now, but we need to find a better long term solution for how to acquire the token.

**Comment by yashgiri** [comment]
The token has been approved merging this PR now.

**Pull request merged**
