### PR TITLE
[sysdig/sysdig-deploy/node-analyzer] Node Analyzer container flags

### PR DESCRIPTION
**Pull request by achandras**
## What this PR does / why we need it:

Adds flags to enable/disable the hostAnalyzer and benchmarkRunner containers. Defaults to true if undefined (as in the case of upgrading with `--reuse-values`)

Builds off of https://github.com/sysdiglabs/charts/pull/420 and https://github.com/sysdiglabs/charts/pull/546

## Checklist

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [x] Title of the PR starts with chart name (e.g. [mychartname])
- [x] Chart Version bumped
- [x] Variables are documented in the README.md (or README.tpl in some charts)
- [x]  Check GithubAction checks (like lint) to avoid merge-check stoppers

Check Contribution guidelines in README.md for more insight.

### CODE REVIEW

**Comment by achandras** [comment]
@kadkins-sysdig @a1ex-var1amov I have used your PRs as a base for these changes, please take a look and let me know if this covers everything

**Comment by mikescholl-sysdig** [comment]
At first glance this looks good to me.

**Review by saltycr3w — COMMENTED** [review]
missing control for `nodeAnalyzer.imageAnalyzer.deploy`

**Comment by mikescholl-sysdig** [comment]
> 

@dthomson-sysdig wouldn't that be covered under `nodeAnalyzer.deploy`?

**Comment by a1ex-var1amov** [comment]
I think @mikescholl-sysdig is correct; this is a part of `nodeAnalyzer.deploy` swither. 
But we'd need to test it, just in case.

**Review by yashgiri — COMMENTED** [review]
LGTM

**Comment by achandras** [comment]
Updated with an additional flag to disable the imageAnalyzer container to allow the kspm agent to run by itself

**Review by saltycr3w — CHANGES_REQUESTED** [review]
https://github.com/sysdiglabs/charts/blob/4f9356f374782ecf9e424bf0f373428d91c62095/charts/node-analyzer/values.yaml#L133-L134

missing a `deploy: true` in the `nodeAnalyzer.imageAnalyzer` section

@achandras

**Comment by saltycr3w** [comment]
@a1ex-var1amov @mikescholl-sysdig 

> I think @mikescholl-sysdig is correct; this is a part of `nodeAnalyzer.deploy` swither. But we'd need to test it, just in case.

https://github.com/sysdiglabs/charts/blob/master/charts/node-analyzer/templates/daemonset-node-analyzer.yaml#L2

If you specify `nodeAnalyzer.deploy: true` it will always deploy the `image-analyzer` even if you only want the `kspm` container, or don't want the `image-analyzer` per what @andrewd-sysdig is after (Agent+KSPM+runtimeScanner)

So we need the individual flag for `image-analyzer` like all the other components.  Because `nodeAnalyzer.deploy: false` will not deploy the nodeAnalyzer DaemonSet at all.

**Comment by achandras** [comment]
@dthomson-sysdig fixed, thanks for catching that.

**Pull request merged**
