### PR TITLE
feat(agent): add extra secrets

### PR DESCRIPTION
**Pull request by jsecchiero**
## What this PR does / why we need it:

Allow passing extra secrets that can be mounted via extraVolumes. This is useful if you need to pass credentials e.g. for pormetheus basic_auth:

```
basic_auth:
    username: prom_user
    password_file: /opt/draios/etc/kubernetes/metrics/password
```

## Checklist

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [x] Title of the PR starts with type and scope, (e.g. feat(agent,node-analyzer,sysdig-deploy):)
- [x] Chart Version bumped for the respective charts
- [x] Variables are documented in the README.md (or README.tpl in some charts)
- [x] Check GithubAction checks (like lint) to avoid merge-check stoppers
- [ ] All test files are added in the tests folder of their respective chart and have a "_test" suffix

Check Contribution guidelines in README.md for more insight.

### CODE REVIEW

**Comment by ironashram** [comment]
@jsecchiero thanks for this, looks reasonable to me, just needs a chart version bump

**Comment by jsecchiero** [comment]
@ironashram done!

**Review by ironashram — APPROVED** [review]
LGTM!

**Pull request merged**
