### PR TITLE
[sysdig] Version bump scripts

### PR DESCRIPTION
**Pull request by deepskyblue86**
## Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)

### CODE REVIEW

**Comment by airadier** [comment]
Thanks!

You'll need to either bump the chart.yaml version (or the linter will fail) or move the scripts to a different location outside the charts/folder.

Do we want to have these scripts shipped in the helm chart package? Maybe we could store them in /scripts at the root of the repository instead of the chart itself?

Otherwise LGTM.

**Comment by balinaveen** [comment]
> Do we want to have these scripts shipped in the helm chart package? Maybe we could store them in /scripts at the root of the repository instead of the chart itself?
> 
I agree it doesn't make sense to ship these scripts as part of the helm chart package. It's for internal use, so moving them up in the directory is a good idea.

**Comment by deepskyblue86** [comment]
I didn't know they'd be shipped this way, that wasn't intentional. I'm moving them.

**Comment by airadier** [comment]
> I didn't know they'd be shipped this way, that wasn't intentional. I'm moving them.

No problem! Yes, they won't break anything in the chart, but the full folder is packaged as a .tar.gz file which is pulled by Helm when installing the chart. So it makes more sense to maintain that scripts in the /scripts folder outside of the chart, as per the latest version.

Thanks!

**Review by airadier — APPROVED** [review]

**Comment by deepskyblue86** [comment]
Please mind I don't have merge grants :upside_down_face:

**Pull request merged**
